name: Call Discord Notification

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, closed]

jobs:
  call-workflow:
    uses: Solware-Agency/git-actions/.github/workflows/discord-notifier.yml@main
    # SUSTITUYE "secrets: ..." por esto:
    secrets: inherit